### ISSUE TITLE
Master and Slave auto addressing (SoftwareBitBang)

### ISSUE THREAD

**Issue by ovedmo** [gioblu/PJON#206]
I found time when master lost connection with unit and remove it from list... but communication still working!! any way to recover list?

**Comment by gioblu** [comment]
Ciao @ovedmo that is strange, the problem seems not related to PJONMaster or PJONSlave classes, but to the reliability of the channel used. Are you using PJDL/SoftwareBitBang ? If so have you places the pull-down resistor as suggested in its README? How often this happens? Always to the same device or randomly?

**Comment by gioblu** [comment]
Ciao @ovedmo I am sorry I have previously misinterpreted your report.
If a slave is removed from the list because not present, can be re-inserted in the list as soon as it will transmit a new packet to the master. Master will detect that id as not present in list and will force the slave to recover the id.

**Comment by ovedmo** [comment]
Hi
I Checked this issue and when slave lost connection even if sending package to master, when master check for slaves state "for(uint8_t i = 0; i < PJON_MAX_DEVICES; i++) {      if(bus.ids[i].state))...." it not recovering... and i get empty list!

**Comment by gioblu** [comment]
Ciao @ovedmo the dynamic addressing procedure has been updated and should now be more stable. Consider that the procedure changed and older/deprecated versions will not be maintained.
