### ISSUE TITLE
Need to know if the power sequence of the master and slave have any significance

### ISSUE THREAD

**Issue by ovedmo** [gioblu/PJON#215]
I powered the master and then the slaves (one wire bus, bitbang) sometime units get id 255!!, why?

**Comment by gioblu** [comment]
Ciao @ovedmo I am sorry if I have answered you with a big delay, but I must takle issues in order and they have a little sedimented. I have worked on this issue, and I was able to replicate the problem. Seems recent changes have affected communication reliablity on master side. Consider that master is obviously in an unreleased state that may be in some case unstable. I am now working locally on a new version of PJONMaster and PJONSlave classes with a better performance. The problem that causes this issue is the same that causes issue: https://github.com/gioblu/PJON/issues/216 for this reason I will close here, and continue discussing it there. Thank you very much for your report.
