### ISSUE TITLE
AnalogSampling - read_byte() detects 1s from noise (actually channel is not busy) --> can_start() returns False all the time

### ISSUE THREAD

**Issue by andrei-volkau** [gioblu/PJON#240]
**Case 1**
I was using Arduino Uno in the following way. The IR LED was used for Transmission/Receiving signals. It worked well. 
![photo_2018-08-02xsdsdsd_10-42-21](https://user-images.githubusercontent.com/12778567/43569990-e5dbc39a-9641-11e8-8578-1f7346946a10.jpg)

**Case 2**
I started to use Arduino Pro Mini in the following way.
![photo_2018-08-02_10-59-25](https://user-images.githubusercontent.com/12778567/43570505-2c13eeae-9643-11e8-9aa1-edcab0a3ab18.jpg)

In both cases, we use  1.1v analog reference.

In case 2, `can_start()` function returned False all the time.
`if(read_byte() != 0B00000000) return false;`
`read_byte()` almost never returned 0B00000000

It means that transmission can not be started. 
So the channel is not busy (there is no active transmission of IR radiation), but `can_start()` says that the channel is busy.   

Case 2: Let me show you low_bit, threshold, high_bit, bit_value.
![photo_2018-08-02dsdsd_11-32-12](https://user-images.githubusercontent.com/12778567/43572374-0723c6e6-9648-11e8-969d-b7a6c5f3292e.jpg)

Usage of solderless breadboard causes noise. So `read_byte()` function tries to read a byte from the noise. The magnitude of the noise is not really high.  The `read_byte()` function detects 1s very frequently. 

Case 1: Let me show you low_bit, threshold, high_bit, bit_value.
![photo_2018-08-02_11-35-55](https://user-images.githubusercontent.com/12778567/43572467-4ebc22aa-9648-11e8-9c45-889c8e5cb8e0.jpg)

There is no solderless breadboard. So there is no noise. So `read_byte()` function almost never detects 1s. 

How we fixed the issue? We fixed the issue in the following way. 
```
uint8_t read_byte() {
      uint16_t bit_value = 0;
      uint16_t high_bit = 10;
      uint16_t low_bit = 10;
      uint8_t byte_value = 0;
```

We are able to use solderless breadboard based robots after applying the fix now. We are using the latest master. Could you please address the issue in a proper way? We are ready to help. We can test the fix.

**Comment by andrei-volkau** [comment]
Hi @gioblu ,
Thank you for the response.

> Having a dedicated pcb would be the best solution to have replicable and reliable results.


We created the following dedicated PCB.
![robot6](https://user-images.githubusercontent.com/12778567/43683813-33c11d1a-989c-11e8-9171-fcbff8a580f4.jpeg)
The PCB is simple. Our first robot includes the following components
1. 2 IR LEDs [each LED is used for Bidirectional Communication];
2. 2 current-limiting SMD resistors  (120Ω)
3. 2 pull down SMD resistors (680kΩ)
4. Arduino Pro Mini 328 - 5V/16MHz
5. Step-Up DC–DC Converter. Here is a picture of it.
![43570505-2c13eeae-96dwdw43-11e8-9aa1-edcab0a3ab18](https://user-images.githubusercontent.com/12778567/43685258-55a009ca-98b8-11e8-83d7-8ce15c7ab439.jpg)
6. one electrolytic filter capacitor, one ceramic filter capacitor

Unfortunately it didn't solved the problem. read_byte() still detects 1s from noise (actually channel is not busy), therefore can_start() returns False all the time. So transmission can not be started. We steel need to hardcode `high_bit` and `low_bit` constants. It helps. So transmission works after that. So the robots are able to communicate with each other. 

Future improvements:
1. We can try to use Arduino Pro Mini 328 - 3.3V/8MHz instead of Arduino Pro Mini 328 - 5V/16MHz. We can use RAW input (MIC5205-3.3BM5, 150mA Low-Noise LDO Regulator). So we can connect  Li polymer accumulator to RAW input. This approach will allow us to get rid from Step-Up DC–DC Converter.  The step-Up DC–DC Converter produces a lot of noise.
2. We can try to add some kind of interference protection to the PCB. I mean that we can protect analog signal from LED on its way to an analog pin.

**I suggest you to use shorter wires to reduce induced interference, if the problem is still there you should just reduce a little the pull down resistance.**
We are using 680kΩ pull down resistor. It seems to be small enough resistance.


**Conclusion**: you suggest to reduce the noise. In case of super low noise,  read_byte() will not dtect 1s from noise when actually channel is not busy.

**Question**: I am not sure that it possible to completely get rid of the noise. So in this case the transmission process will not happen at all.  read_byte() will detect 1s from noise (actually channel is not busy), therefore can_start() will return False all the time.
In case of our best robot, hard coding of the following constants solves the issue. 
```
uint8_t read_byte() {
      uint16_t bit_value = 0;
      uint16_t high_bit = 10;
      uint16_t low_bit = 10;
      uint8_t byte_value = 0;
```
Are you completely sure that the issue is related to hardware only? It means that the only way to resolve the issue is complete reducing of noise. It means that even low level of noise is not acceptable. Is there any software fixes that might address the issue?

**Comment by gioblu** [comment]
Ciao @andrei-volkau yes, you are absolutely right, for sure this must be solved in software.
Thank you for your report, looking into it, obviously meanwhile you can get away with your temporary patch. 

My compliments for the great work 👍 
I would be really curious to see a video of the robots roving around!!
Keep me updated and let me know if you need help.

one thing, if you are using continuous rotation servos one interesting thing is to pull a couple of wires from the poles of the dc motor and sample with analogReading the voltage. That is directly proportional to the rotation of the motor.

I have the codebase ready to read that signal and let the robot move receiving cartesian coordinates (although is something I have written 8 years ago could be useful for you now):

====================================

Thanks to this code, you can control the robot with Cartesian coordinates. In the same way, with a simple radio link, in real time obtain the position of the robot. Let's say that the possibilities that are open are almost endless and the game does not stop immediately as with normal robots with continuous rotation servos, which actually before today were rather "limited".

### Integration of Voltages 

I welded two cables to the two poles of the DC motors inside the servomotors. This will allow us to perceive the voltage present in the power supply circuit through the analogue ports. The behavior of this feedback is as follows:

- port1 4.35v gate2 0.25v = full forward
- port1 2.35v porta2 2.35v = stationary motors
- port1 0.25v port2 4.35v = back all

What we need to do now is to frame which pair of 4 cables we have welded will have a high voltage while the robot goes forward. To do this simply call the two commands to move the servomotors (in an empty sketch) and print the 4 values ​​of the 4 soldered feedback in serial mode.

Here is the code you need, **remember to include the Servo.h** library:
```cpp
Servo leftservo; // create servo object to control to servo
Servo rightservo; // create servo object to control to servo
 
void setup () {
 leftservo.attach (9);
 rightservo.attach (10);
 Serial.begin (9600);
}
 
void loop () {
 leftservo.write (180); // the two servos must rotate so that the robot moves forward
 rightservo.write (0);
 Serial.print ("left ENGINE - if high v1Left");
 Serial.print (analogRead (2));
 Serial.print ("if low v2Left");
 Serial.print (analogRead (3));
 Serial.print ("right engine - if high v1Right");
 Serial.print (analogRead (4));
 Serial.print ("if high v2Right");
 Serial.println (analogRead (5));
}
```

As you can see it will be enough to clarify which of the two poles has a high voltage during the forward movement to have found the correct wiring. With this we use the integration "scaling" value weight depending on the cycle duration:
```cpp
movement = v1Right * (endTime - startTime);
```
As you can see the pole with high voltage, during the forward movement it is multiplied by the duration of the loop.

### Wheel movement correction

Knowing the voltage in the two power circuits it is possible to correct the movement of the wheels so as to obtain a straight motion or coordinated wheel rotation. To do this the  `correctStop`, `correctGo` and `correctRotation` are used. Thanks to these three functions the driving of the motors is self-regulated to obtain fluid and coordinated movements.

### The calculation of the distance traveled in mm 
Always using the power supply voltage feedback, let's calculate how many mm the robot has traveled. What we do is integrate the voltages and frame the sum of these in order to obtain a complete and precise revolution of the wheel. To do this, I created a variable:
```cpp
float oneRotationValue = 1125000000; // traveled for a spin of the wheel
```
This variable contains the value of the travelled variable that corresponds to a wheel revolution. To make debugging and setting of this variable just call this command: ** goForward (50, 251); ** where 50 is the speed value between 0 and 100 and 251 are the mm that we ask the robot to travel (in this case our wheels being 8cm diameter have a rolling surface of 251mm). Clearly it is unlikely that the value that I have entered corresponds to you for a turn of the wheel, you will need to calibrate it to obtain a fair amount of precision.

The rest is simple:
```cpp
const float wheelDiameter = 80; // wheel diameter in mm
const float wheelCircumference = M_PI * wheelDiameter; // circumference rotates in mm
const float wheelsDistance = 134; // distance between the two wheels in mm
const float wheelsDistanceCircumference = M_PI * wheelsDistance; // circ. rotation
const float oneDegreeTravel = wheelsDistanceCircumference / 360; // mm to rotate 1 °
const float millimeter = oneRotationValue / wheelCircumference; // transformation in mm
```
As you can see you just enter the diameter of your wheel and the distance between the two wheels because the software calculate all the rest (this thing I go very proud of! Thanks to the diameter of the wheel and the value we found previously the software calculates how much integrated voltage in time correspond to 1mm, instead knowing the distance between the two wheels and the previous figure calculates how many integrated volts will need to rotate by 1 °.

### Drive the robot using coordinates

Having clarified the distance and rotation calculation done, we introduce the concept of Cartesian plane and absolute angle that allows the robot to calculate its current position with respect to the starting position.

To calculate the rotation required to reach the required point, the tangent arc of the difference between the previous coordinates and the current ones is used:
```cpp
 float angle = atan2 (dy, dx) * (180 / M_PI);
```
After which, using the simple Pythagorean theorem, the space that must be traveled in a straight line to reeach the required point is calculated:
```cpp
 goForward (40, sqrt (square (right) + square (dy)));
```
As you can see it is not as complex as it seems, even if it was a nightmare to get this result.

From these two statements we have developed the function `goXY (x, y);` which allows you to request the robot to reach a point passing coordinates.

```cpp
// CONTROLLO SERVI
Servo leftServo;  
Servo rightServo; 
//////////////////////
int v1Left = 0;  // val poloi servo sn - pole1 servo left
int v2Left = 0;  // val polo2 servo sn - pole2 servo left
int v1Right = 0;  // val polo1 servo dx - pole1 servo right
int v2Right = 0;  // val polo2 servo dx - pole2 servo right
//////////////////////
int leftThrottle = 90; // val servo sn - left servo variable
int rightThrottle = 90; // val servo dx - right servo variable
int leftStop = 90; // val stop servo sn - left servo stop calibrated value
int rightStop = 90; // val stop servo dx - right servo stop calibrated value
//////////////////////
float millimetersTravelled = 0;    // travelled distance in mm
float oneRotationValue = 1125000000; // travelled value for 1 wheel rotation
//////////////////////
const float wheelDiameter = 80;// wheel diameter in mm
const float wheelCircumference = M_PI * wheelDiameter; // circ. wheel in mm
const float wheelsDistance = 134;// wheels distance in mm
const float wheelsDistanceCircumference = M_PI * wheelsDistance;// circ. rotation
const float oneDegreeTravel = wheelsDistanceCircumference / 360; // mm to rotate 1 deg
const float millimeter = oneRotationValue / wheelCircumference; // scaled in mm

float x = 0;  // actual  x
float y = 0;  // actual y
float absoluteAngle = 0; // actual heading in deg
////////////////////////

void setup() {
 leftServo.attach(9); 
 rightServo.attach(10); 
 pinMode(irEmitter, OUTPUT);     
 Serial.begin(9600);
 stopServos(); //diamo il comando stop ai servi
}

//////////////////////READ MOTOR POLES/////////////////////////////////////////
void readVs() { //leggiamo i 4 poli dei servi
  v1Left = analogRead(2);                       
  v2Left = analogRead(3);
  v1Right = analogRead(4);
  v2Right = analogRead(5);
}
//////////////////////CORRECT SERVO SPEEDS DURING MOVEMENTS////////////////////
void correctStop() {
 readVs();
 if(v1Left &gt; v2Left){leftThrottle--;}
 if(v1Left &lt; v2Left){leftThrottle++;}
 if(v1Right &gt; v2Right){rightThrottle++;}
 if(v1Right &lt; v2Right){rightThrottle--;}
}

void correctGo() {
 readVs();
 if(v1Left &gt; v2Right){leftThrottle++;}
 if(v1Left &lt; v2Right){leftThrottle--;}
}

void correctRotation(float dir) {
 readVs();
 if(dir &gt; 0) {
  if(v1Left &gt; v2Right){leftThrottle++;}
  if(v1Left &gt; v2Right){leftThrottle--;}
 }
 else {
  if(v1Left &gt; v2Right){leftThrottle--;}
  if(v1Left &gt; v2Right){leftThrottle++;}
  }
}
////////////////////////WRITE SERVOS///////////////////////////////////////////
void writeServos() {
  // constrain servo speeds 0-180
  leftThrottle = constrain(leftThrottle, 0, 180);
  rightThrottle = constrain(rightThrottle, 0, 180);
  leftServo.write(leftThrottle);
  rightServo.write(rightThrottle);
}

void stopServos() {
  leftThrottle = leftStop;
  rightThrottle = rightStop;
  writeServos();
}
////////////////////////CALIBRAZIONE POSIZIONE DI STOP/////////////////////////
void stopCalibration() {
  for(int t = 0; t &lt; 2000; t++) {
    correctStop();
    writeServos();
    delay(1);
  }
  // aggiorna le posizioni di stop
  leftStop = leftThrottle;  
  rightStop = rightThrottle;
}
//////////////////////FUNZIONE AVANZAMENTO/////////////////////////////////////
void goForward(int speed, float distance) {
 float travelled = 0, movement = 0;
 long startTime = 0, endTime = 0;
 int accelerating = 1;
 int leftSpeed = map(speed, 0, 100, leftStop, 180);
 int rightSpeed = map(speed, 0, 100, rightStop, 0);
 while(travelled &lt; distance) {
   startTime = micros();
   correctGo();
   writeServos();
   if(accelerating) {
    if(leftThrottle &lt; leftSpeed){leftThrottle += 5;}
    if(rightThrottle &gt; rightSpeed){rightThrottle -= 5;}
    if((leftThrottle &gt;= leftSpeed) || (rightThrottle &lt;= rightSpeed)){accelerating = 0;}
   }
   endTime = micros();
   movement = v1Right * (endTime - startTime);
   travelled += movement / millimeter;
 }
 stopServos();
 float angle = (M_PI / 180) * absoluteAngle;
 x += travelled * cos(angle);
 y += travelled * sin(angle);
 millimetersTravelled += travelled;
}
//////////////////FUNZIONE ROTAZIONE///////////////////////////////////////////
void rotate(int angle) {
 float travelled = 0, movement = 0;
 long startTime = 0, endTime = 0;
 if(abs(angle - absoluteAngle) &lt; 1){return;}
 if(abs(angle - absoluteAngle) &gt; 180) {
  if(angle &lt; 0){absoluteAngle -= 360;}
  else{absoluteAngle += 360;}
 }
 angle -= absoluteAngle;
 stopServos();
 leftThrottle = (angle &gt; 0) ? 0 : 180;
 rightThrottle = (angle &gt; 0) ? 0 : 180;  
 while(travelled &lt; (wheelsDistanceCircumference / 360) * abs(angle)) {
  startTime = micros();
  correctRotation(angle);
  writeServos();  
  endTime = micros(); 
  movement = (angle &gt; 0 ? v1Right : v2Right) * (endTime - startTime);
  travelled += movement / millimeter;
 }
 stopServos();
 absoluteAngle = absoluteAngle + angle;
}
//////////////////FUNZIONE XY//////////////////////////////////////////////////
void goXY(float x1, float y1) {
 float dx = x1 - x;
 float dy = y1 - y;
 if(abs(dx) &lt; 2){dx = 0;}
 if(abs(dy) &lt; 2){dy = 0;}
 if(dx == 0 && dy == 0){return;}
 float angle = atan2(dy, dx) * (180 / M_PI);
 rotate(angle);
 goForward(40, sqrt(square(dx) + square(dy)));
}

void loop() {
  goForward(40, 500);
  delay(5000);
  absoluteAngle = 0;
  x = 0; 
  y = 0;
  goXY(200, 0);
  goXY(200, 200);
  goXY(0, 200);
  goXY(0, 0);
  delay(5000);
}
```

**Comment by gioblu** [comment]
@andrei-volkau I would iterate the board and try to see if you can read from 4 LEDs and share the estimated position of each robot to the other and keep them in formation using coordinates.

**Comment by gioblu** [comment]
Ciao @andrei-volkau problem solved, thank you very much for reporting this.
I am really curious to know how the project is going, feel free to ask for support if necessary.
Closing here, feel free to reopen if required.
