### ISSUE TITLE
Problem interfacing ESP32 and Arduino Pro Mini (Atmega328P 16MHz) 

### ISSUE THREAD

**Issue by maniekq** [gioblu/PJON#260]
I have successfully established PJON communication between two ESP32s, but I have a problem with communication between ESP32 and Arduino Pro Mini (Atmega328P 16MHz 5V). 

ESP32 (port 25) is connected through level shifter with Pro Mini (port 10). I've added 2.2k pull-down resistor between ESP32 commmunication port and level shifter. I've also tried with various pull-down resistors on the Pro-Mini side (between 600 and 10k) without success.

Currently when running NetworkAnalysis example with ESP32 as transmitter I get following results:
```
Packet Overhead: 10B - Total: 530B
Bandwidth: 1590B/s
Data throughput: 1060B/s
Packets sent: 53
Mistakes (error found with CRC): 0
Fail (no acknowledge from receiver): 6
Busy (Channel is busy or affected by interference): 0
Accuracy: 100.00 %
```

Which looks fine to me. When I run NetworkAnalysis example with Pro Mini as transmitter the results are:
```
Packet Overhead: 10B - Total: 0B
Bandwidth: 0B/s
Data throughput: 0B/s
Packets sent: 0
Mistakes (error found with CRC): 0
Fail (no acknowledge from receiver): 55
Busy (Channel is busy or affected by interference): 0
Accuracy: nan %
```

My question is - should I keep trying with different values of pull-down resistor on the Pro Mini side to get this running? If so - could you suggest what values should I try with? Or maybe I should try changing the pull-down resistor on the ESP32 side? 

Please let me know if you need any further details.

**Comment by gioblu** [comment]
Ciao @maniekq I am not sure what is the cause, but it could be because of the level shifter, are you sure the shifter channel is bidirectional? 

Consider that ESP8266 IO's 5v tolerance has been verified by the Espressif CEO himself on facebook: https://www.facebook.com/groups/1499045113679103/permalink/1731855033731442/?hc_location=ufi

I have run extended tests Arduino <-> ESP32 using a bare wire and it all works fine although I am not sure if to suggest this configuration on a production setup.

It may help to try with a bare wire and just current limiting resistors to verify it works without level shifter.

**Comment by maniekq** [comment]
Hi @gioblu. Thank you for replying. I've tried with bare wire (no level shifter), but it didn't helped. That made me think though. I've tried with another Pro Mini to be sure it is not defective and the result was exactly the same.
What I've finally found is that port 10 was a bad choice with the clone of Pro Mini I own. I've changed port to 11 and communication works correctly both ways now. I am closing this issue then.
Thank you for your help and great work with PJON!
