### ISSUE TITLE
Wiring Diagram ESP8266 - Arduino

### ISSUE THREAD

**Issue by MichMich** [gioblu/PJON#33]
Since PJON is now compatible with the ESP8266 (which is a 3v3 device), it might be helpful to supply a wiring diagram in the readme on how to connect a 3v3 device (ESP8266) to an 5v device (Arduino).

Keep up the good work!

**Comment by domonetic** [comment]
simple. you need use a shift level. or zener to drop down.

https://dl.dropboxusercontent.com/u/1641023/ESP8266%20BASIC.png

Please if you need help send me email.

**Comment by gioblu** [comment]
Hi Mich, domonetic, I would make a wiki page for ESP.
@domonetic would you help me a little with this part?

**Comment by gioblu** [comment]
Ciao @MichMich I had success with these modules:
![unnamed2](https://cloud.githubusercontent.com/assets/764497/13759986/251b1660-ea31-11e5-9310-64b22b5e02a2.png)
![unnamed](https://cloud.githubusercontent.com/assets/764497/13759988/279422a6-ea31-11e5-8add-22c49c599234.png)

As suggested by user @240974a You just need to put pulldown resistors 1-2 kOhm to signal lines on both sides (3.3v and 5v). So low value resistors because there 10kOhm pullup resistors on the converor board. If you remove pullups from the board, it's possible to use 10 kOhm pulldown resistors.

**Comment by domonetic** [comment]
@gioblu yes of course . I help tou

**Comment by itsjustvenky** [comment]
Using level shift is always better because the data transmission is faster on level shifter compare to a voltage divider or zenor diode setup.

**Comment by gioblu** [comment]
Ciao @domonetic .
I am trying to understand how to give you access to the wiki, so we can work together to the ESP8266 interfacing page. Will write you soon

**Comment by domonetic** [comment]
simple. i write a new entry and you accept changes

**Comment by gioblu** [comment]
Thank you! Following the actual index standard the title is "ESP8266 interfacing".
I really appreciate your support.

**Comment by gioblu** [comment]
CIao! aperepel created a wiki page, I also worked a little on that and this is the result:
https://github.com/gioblu/PJON/wiki/ESP8266-interfacing

Lets me know if you think is enough or you would add something else.

**Comment by MichMich** [comment]
Cool! Maybe You could add the zener diode version as welk.

**Comment by gioblu** [comment]
Ciao @MichMich I am studiyng the alternatives, and will practically try.
I will then add all the acquired info in the wiki!

Hope you are having good tinkering.

**Comment by MichMich** [comment]
I will start my test setup for my PJON curtain system in a few weeks. If I run into nice solutions, I'll add it to the Wiki.

**Comment by aperepel** [comment]
Hi @gioblu I've made some corrections to the resistor values (all hail the new shiny logic analyzer for this!) :)

The Uno side requires 1.5K pulldown (2.2K will most probably work as well), otherwise the pin flips high after ACK/NACK. Note that 10K pulldown here results in some noise and, as a result, retransmissions.

The esp8266 is ok with 10K pulldown.

Ran network tests with either board being a sender, all stable now.

High-speed mode **doesn't work** in this setup, only compatibility mode (default). I've updated my previous Fritzing project here: http://fritzing.org/projects/pjon-with-uno-and-esp8266nodemcu

Test results:
```
Absolute com speed: 1867.20B/s
Practical bandwidth: 1556.00B/s
Packets sent: 778.00
Mistakes (error found with CRC) 0.00
Fail (no answer from receiver) 0
Busy (Channel is busy or affected by interference) 0
Accuracy: 100.00 %
```

**Comment by gioblu** [comment]
ciao @aperepel, in PJON.h are still not defined timing values for the mode COMPATIBILITY_MODE false for ESP. In any case my suggestion if you want to work on timing tweaking to work on the branch I personally sent you and some other contributors, 2.0 is much more organized and easy to work with timing. I will soon also create the branch as you correctly suggested.

I updated wiki according to your results. Thank you so much for your support.

**Comment by aperepel** [comment]
Thanks @gioblu . On the same wiki, the GND to GND connection for esp8266-esp8266 made no difference in my tests. Literally 1 wire was ok. Maybe make a note there, it could depend on how boards are powered.
Now that I've got the right tools, I might look into tuning/adding Fast & Overdrive modes. In the future :)

**Comment by gioblu** [comment]
We can consider the wiki page now satisfactory?
